### ISSUE TITLE
errors when compiling. error: ‘istream_iterator’ was not declared in this scope

### ISSUE THREAD

**Issue by saikrishna-1996** [subokita/Robust-Text-Detection#11]
I use opencv2.4 on my ubuntu 14.04. I just installed tesseract using "sudo apt-get install libtesseract-dev". I compiled main.cpp and I am getting the error as shown in the screenshot
kindly help!

![screenshot from 2015-12-15 19 56 50](https://cloud.githubusercontent.com/assets/7241706/11813203/04b5c4d6-a366-11e5-8ca4-c4ee87ea988b.png)

![screenshot from 2015-12-15 19 59 13](https://cloud.githubusercontent.com/assets/7241706/11813251/5603707c-a366-11e5-9bd5-775e7da7c4e1.png)

**Comment by subokita** [comment]
It seems like you're using C++98. I'm using C++11, which allows things like for each loop. You should try to use C++11 compiler. Not sure how to enable that on your side though
