### ISSUE TITLE
cant get MSER class

### ISSUE THREAD

**Issue by kalvinkrishna** [subokita/Robust-Text-Detection#12]
cant you explain me where i must pust MSER class include on my code?? i read your code but i cant get it where is MSER class at all thanks

**Comment by subokita** [comment]
http://docs.opencv.org/2.4/modules/features2d/doc/feature_detection_and_description.html

**Comment by kalvinkrishna** [comment]
Thank you for your replay sir, I mean when i read your code on class RobustText.cpp and i found 

  **MSER** mser( 8, param.minMSERArea, param.maxMSERArea, 0.25, 0.1, 100, 1.01, 0.03, 5 );
  mser(grey, contours);

i still not get any idea how is come, i search on include header i'm not find inlclude like #include <MSER.h> or etc. can you explain where i can referense that??  its refrense by library or use your own code? and if its reference by library what include header on your code to call them?

thank you.

**Comment by subokita** [comment]
It's part of opencv2 header, i.e. opencv.hpp, which in turn includes features2d.hpp. There's MSER stuff in there. But it was older opencv, so things might have change. And I don't update it anymore.

**Comment by kalvinkrishna** [comment]
thank you sir, i get this right now, nice to meet you. thanks for your great answer
